services:
  mysql8.0:
    image: mysql/mysql-server:latest
    environment:
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_PASSWORD: '${DB_ROOT_PASSWORD}'
    volumes:
      - 'data:/var/lib/mysql'
    ports:
      - '${DB_PORT}:3306'
    networks:
      - test-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: 'mysql8.0'
      PMA_PORT: '3306'
      PMA_USER: '${DB_USERNAME}'
      PMA_PASSWORD : '${DB_PASSWORD}'
    ports:
      - '8080:80'
    networks:
      - test-network

networks:
  test-network:
    driver: bridge

volumes:
  data:
    driver: local
